Add integration tests and ci jobs
canonical/charm-lxd-integrator pull request #16
Opened 2024-02-05 11:01 UTC by jat-canonical

This commit adds 
- Github Actions CI jobs to build and test the charm
- Add integration tests to validate relation for the charm

2024-02-06 09:22 UTC, ajanon requested changes
One small question.

Also, what's the policy around copyright headers for charms? Is that something you should put in the files you add?

2024-02-06 09:22 UTC, ajanon commented on src/interface.py
> +            json.loads(current_node["trusted_certs_fp"])
Shouldn't this be .get with a default value, in case the dictionary doesn't have the key? Or is that impossible?

2024-02-06 09:29 UTC, jat-canonical commented on src/interface.py
> +            json.loads(current_node["trusted_certs_fp"])
I was asking myself the same question when I saw this. Ideally I would like to put a .get in there but the code down below might get a side effect from the empty value hence decided against it. Also I think this is supposed to break anyway if there is problem with this as it is on a critical code path and this piece of data is written by this code itself.

2024-02-06 09:30 UTC, jat-canonical commented
> One small question.
> 
> Also, what's the policy around copyright headers for charms? Is that something you should put in the files you add?

Good question, I am not sure either since these are open repos. @morphis any idea ?

2024-02-06 10:05 UTC, ajanon commented on src/interface.py
> +            json.loads(current_node["trusted_certs_fp"])
I see, thanks for the answer!

2024-02-06 17:04 UTC, morphis commented
> Good question, I am not sure either since these are open repos. @morphis any idea ?

Yes, we should add them. See [here](https://github.com/canonical/grafana-k8s-operator/blob/main/src/charm.py) for a good example.

2024-02-06 18:51 UTC, morphis approved these changes
LGTM

We can do copyright headers in a separate PR or this one. Will leave this up to you. However we should apply them across all our charms, at best in one go.

2024-02-07 09:55 UTC, ajanon approved these changes
LGTM

2024-02-07 10:54 UTC, merged